const TOKEN_SECRET = process.env.TOKEN_SECRET || 'JIANGRENSECRET';
const AWS_REGION=process.env.AWS_REGION;
const AWS_ACCESS_KEY_ID=process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY=process.env.AWS_SECRET_ACCESS_KEY;
const GMAIL_AUTH_USER = process.env.GMAIL_AUTH_USER;
const GMAIL_AUTH_PASS = process.env.GMAIL_AUTH_PASS;
const GMAIL_AUTH_HOST = process.env.GMAIL_AUTH_HOST;
const GMAIL_AUTH_PORT = process.env.GMAIL_AUTH_PORT;

export {
	TOKEN_SECRET,
	AWS_REGION,
	AWS_ACCESS_KEY_ID,
	AWS_SECRET_ACCESS_KEY,
	GMAIL_AUTH_USER,
	GMAIL_AUTH_PASS,
	GMAIL_AUTH_HOST,
	GMAIL_AUTH_PORT
};
